[package]
name = "rpg_cli"
version = "0.1.0"
authors = ["Joe Teahen"]
edition = "2021"

[[bin]]
doc = false
name = "rpg_cli"

[build-dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"

[dependencies]
rand = "0.8"
text_io = "0.1.12"
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"
